### ISSUE TITLE
the zigbee module is not working - How to fix ?

### ISSUE THREAD

**Issue by ds2k5** [patience4711/ESP32-read-APS-inverters#12]
Hello,

![ESP32-ECU](https://github.com/patience4711/ESP32-read-APS-inverters/assets/11292286/cfde5bdb-db8b-40fc-9b02-c20a216c16db)

flashed the file: **CC2530ZNP-with-SBL.hex** to the CC2530

Wiring:

**ESP32      CC2530**
  3.3V    <->  3.3V
  GND    <-> GND
  GPIO5 <-> RST
  GPIO7 <-> R03
  GPIO8 <-> R02

ESP32

https://www.flickr.com/photos/jgustavoam/40089095211

CC2530 from ChdTech

https://www.zigbee2mqtt.io/assets/img/webee_cc2530_cc2591_pinlayout.c476b9b5.png

What did I wrong ?

Console Log:

screen /dev/ttyUSB0 115200

```
checkZigbeeRadio
  sendZB FE00270027
 readZB nothing to read
retrying..
  sendZB FE00270027
 readZB nothing to read
retrying..
  sendZB FE00270027
 readZB nothing to read
retrying..
zb down
hc starting coordinator
starting coordinator
cordinator init 1
init zb coordinator
cordinator init 1
ZB module hard reset
cmd : 0
zb send cmd 0
  sendZB FE03260503010321
 readZB nothing to read
cmd : 1
zb send cmd 1
  sendZB FE0141000040
 readZB nothing to read
cmd : 2
zb send cmd 2
  sendZB FE0626050108FFFFAD8FE
 readZB nothing to read
cmd : 3
zb send cmd 3
  sendZB FE032605870100A6
 readZB nothing to read
cmd : 4
zb send cmd 4
  sendZB FE0426058302D8A74
 readZB nothing to read
cmd : 5
zb send cmd 5
  sendZB FE062605840400000100A4
 readZB nothing to read
cmd : 6
zb send cmd 6
  sendZB FE0D240014050F0001010002000015000020
 readZB nothing to read
cmd : 7
zb send cmd 7
  sendZB FE00260026
 readZB nothing to read
send normal ops initCmd = 2401FFFF1414060001000F1EAD8FBFB1100000D6030FBD3
  sendZB FE162401FFFF1414060001000F1EAD8FBFB1100000D6030FBD393
 readZB nothing to read
zb initializing ready, now check running
checkZigbeeRadio
  sendZB FE00270027
 readZB nothing to read
retrying..
  sendZB FE00270027
 readZB nothing to read
retrying..
  sendZB FE00270027
 readZB nothing to read
retrying..
starting ZB coordinator failed
nightmode

```

**Comment by patience4711** [comment]
The wiring is wrong, the rx2 and tx2 pins are gpio16 and 17 please read the wiki (hardware).  If it still doesn't work please look in the isues for the esp-ecu [like here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/issues/98) this is a problem that keeps popping up, its always the wiring or improper firmware.

**Comment by ds2k5** [comment]
thanks.... looks like I killed my CC2530 :-(

**Comment by patience4711** [comment]
Thats bad news, I thought you had it flashed already. You can only fry it when vvc too high.

**Comment by ds2k5** [comment]
yes I flashed with a SmartRF

I reversed 3V and GND by connecting to the ESP32
looks like the CC2530 did not have a reverse polarity protection

**Comment by patience4711** [comment]
Too bad, i hope you have better luck next time.

**Comment by ds2k5** [comment]
thank you

**Comment by ds2k5** [comment]
got a new cc2530 flashed the firmware file: CC2530ZNP-with-SBL.hex but had the same issue: the zigbee module is not working.

![grafik](https://github.com/patience4711/ESP32-read-APS-inverters/assets/11292286/40d8235f-5d9e-4bed-a5f4-92cabfdfa7d4)

![grafik](https://github.com/patience4711/ESP32-read-APS-inverters/assets/11292286/6ac726a1-6203-4363-8d92-1e3f92a52df2)

https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/blob/main/cc25xx_firmware.zip

ESP32 CC2530
3V <-> 3V
GND <-> GND
D5 <-> RST
RX2/GPIO16 <-> P03
TX2/GPIO17 <-> P02

[esp32-ecu-0.8.zip](https://github.com/patience4711/ESP32-read-APS-inverters/files/13650055/esp32-ecu-0.8.zip)

**Comment by patience4711** [comment]
Before anything else you should ensure that the zigbee is working, (console health) 

I don't know what you did here, looks like you have registered 8 inverters. To get rid of them you can visit the console and click "help". 10;erase removes all inverterfiles.

**Comment by ds2k5** [comment]
>Before anything else you should ensure that the zigbee is working, (console health)

looks good did not give the message again


>I don't know what you did here, looks like you have registered 8 inverters. To get rid of them you can visit the console and click "help". 10;erase removes all inverterfiles.

ENTER S/N of Inverter and klick to add button

**Comment by patience4711** [comment]
I would like to close this issue with a conclusion that is helpfull to others. The problem was that the zigbeemodule didn't work. So what is the present state, does it work now? What was the solution?

**Comment by ds2k5** [comment]
>I would like to close this issue

ok thanks for your help

> What was the solution?

may I did not wait long enough
