### ISSUE TITLE
Flashing with esptool.py

### ISSUE THREAD

**Issue by jmguilbert** [patience4711/ESP32-read-APS-inverters#15]
Hey Patience4711.
Can you help me by giving me the complete command line needed to flash your project on an esp32 with esptool.py (ubuntu). I've been searching for nights...and I'm failing.
A big thank you to you.
JM.

**Comment by patience4711** [comment]
Sorry i never used that. Look [here](https://github.com/patience4711/ESP32-read-APS-inverters/issues/5) for inspiration:
