### ISSUE TITLE
Firmware for ESP32-C3

### ISSUE THREAD

**Issue by sylvaing26** [patience4711/ESP32-read-APS-inverters#18]
Hello,
can you compile your program for ESP32-C3 chip please ?
I've tried whith ArdunoIDE and your code source without success

Thanks

**Comment by patience4711** [comment]
[here](https://github.com/patience4711/ESP32-read-APS-inverters/blob/main/ESP32-ECU_v0-9_exp.ino.esp32c3.bin) it is, i cannot test so don't know it it will work

**Comment by sylvaing26** [comment]
Thanks,
but it did not work.
My chip is ESP32C3 Dev Module

**Comment by patience4711** [comment]
Thanks but in what way it didn't work?

**Comment by sylvaing26** [comment]
It doesn't boot

Le mer. 7 févr. 2024, 13:32, patience4711 ***@***.***> a
écrit :
