### ISSUE TITLE
CONNECT TO WIFI VIA BLUETOOTH

### ISSUE THREAD

**Issue by patience4711** [patience4711/ESP32-read-APS-inverters#19]
To simplify the wifi connection procedure, i am experimenting with the bluetoothserial library. As an alternative for the complex, program space consuming and sometimes unreliable captive portal.

This works very good: When the wifi connection fails -or on request via the menu-, the bluetooth is started (the blue led goes on) .  The ESP enters an infinite loop where it only jumps out when timed out (after 5 min) or on user input. 
We can connect to the ESP32 via an app on our phone, (like Serial Bluetooth Terminal). After authentication with the admin password or the chipid, we can request system info (type 'info'), interactively set -or wipe- the wificredentials, set the security level and set the admin password. When done we can exit (type 'exit') and the esp reboots into normal operations. The bluetooth doesn't exist anymore then.

When the ESP can't connect f.i. after a grid failure when the router isn't up yet, it enters the loop but times out after 5 minutes. Then the esp reboots and will try again to connect. 

In the Serial Bluetooth Terminal app we can assign actions to buttons so the connection can be made just by pushing 3 buttons and a 'y'. Very quick and handy.

The enormous overhead of that wifimanager can be cleaned up this way.

When someone wants to try it, [you can find it here](https://github.com/patience4711/ESP32-read-APS-inverters/blob/main/ESP32-ECU_v0-9_BT.ino.esp32.bin)

More details you can find [here](https://github.com/patience4711/ESP32-WIFIMANAGER-VIA-BLUETOOTH/tree/main)

**Comment by APSjens** [comment]
Hello patience4711,

First I want to say thank you very much for developping such an excellent program...
I just tried the new bluetooth version but had not luck with the authentication. After "authentication" the esp32 answers with "please enter your admin password". Wether I put in the chipid or the long number, it is accepted! The answer is: "You entered 123..." But in the same moment the esp32 says "wrong passwd". What did I wrong? Best regards, Jens

APsystems YC600, ESP32-WROOM-32U, CHD tech CC2530,

**Comment by APSjens** [comment]
Hi patience4711,
to be more precise it is that I'm not able to put in the right password. It is not the chipid or 12346789. Could you give me some hints what is going wrong? Best regards, Jens

**Comment by patience4711** [comment]
Did you check that the cr and lf are disabled in the serial-bt app ?

**Comment by APSjens** [comment]
Thanks a lot, that was it!
