### ISSUE TITLE
Integrate the ccloader flasher

### ISSUE THREAD

**Issue by bs-github** [patience4711/ESP32-read-APS-inverters#2]
Following the footprints of the tasmota project that integrated the ccloader (https://tasmota.github.io/docs/CCLoader/),
I'd like to try to add the flashing of the cc25xx zigbee module firmware right into this project. 
Maybe embedding the firmware for the cc25xx too.

Do you think that is a good idea?

Ideally I would connect all the pins needed for flashing and operation.
Best, not to have to disconnect any of them for operation.
Which pins would you recommend to use for that?

Or putting the question the other way around, which pins are already occupied and should not be used?

**Comment by patience4711** [comment]
@bs-github For something you use maybe once or twice in a lifetime, it seems a lot of work to me. The pins in use you can find in the wiki. Good luck with this.
