### ISSUE TITLE
client ID is not saved

### ISSUE THREAD

**Issue by IngoX76** [patience4711/ESP32-read-APS-inverters#22]
Hello everyone,
I have the problem that the client ID in mosquitto doesn't seem to be saved.  After every restart I have to enter the client ID again. Is there a solution for this?

**Comment by patience4711** [comment]
Sorry, i overlooked this issue. 
The original idea was to auto generate a userid based on the chipid of the esp but i forgot to implement that. 

If you update the software with [this bin (v0-9a)](https://github.com/patience4711/ESP32-read-APS-inverters/blob/main/ESP32-ECU_v0-9a.bin) the userid will be saved.
Please let me know if it works.
